In [173]:
import pandas as pd

In [174]:
test = pd.read_csv("../../dataset/test/test_data.csv")
test

,id,sentence,subject_entity,object_entity,label,source
0,0,지난 15일 MBC '탐사기획 스트레이트'가 이 사실을 보도했다.,"{'word': 'MBC', 'start_idx': 7, 'end_idx': 9, ...","{'word': '탐사기획 스트레이트', 'start_idx': 12, 'end_i...",100,wikitree
1,1,사랑스러운 ‘프린세스 프링’의 이름은 봄의 공주님: Princess(s)Pring이...,"{'word': '프린세스 프링', 'start_idx': 7, 'end_idx':...","{'word': '공주', 'start_idx': 84, 'end_idx': 85,...",100,wikipedia
2,2,"한편, 본인(이근안)을 모델로 한 MBC 특집드라마 가 1995년 6.25 특집극으...","{'word': '경찰', 'start_idx': 121, 'end_idx': 12...","{'word': '1995년', 'start_idx': 31, 'end_idx': ...",100,wikipedia
3,3,정창손은 김질과 같이 대궐로 달려가 고변하며 '신은 실로 모르고 김질만 혼자 참여하...,"{'word': '세조', 'start_idx': 78, 'end_idx': 79,...","{'word': '정창손', 'start_idx': 0, 'end_idx': 2, ...",100,wikipedia
4,4,"당시 민주당 이진련 시의원은 권영진 시장에게 ""긴급 생계자금을 왜 현금으로 지원하지...","{'word': '민주당', 'start_idx': 3, 'end_idx': 5, ...","{'word': '권영진', 'start_idx': 16, 'end_idx': 18...",100,wikitree
...,...,...,...,...,...,...
7760,7760,코로나19 방역 조치의 일환으로 국민의 움직임을 통제하려는 정부의 시도를 이탈리아 ...,"{'word': '정부', 'start_idx': 33, 'end_idx': 34,...","{'word': '이탈리아', 'start_idx': 41, 'end_idx': 4...",100,wikitree
7761,7761,선 연구원은 “위식도역류질환치료제인 케이캡이 92억원 판매되면서 2019년 연간 3...,"{'word': '종근당', 'start_idx': 133, 'end_idx': 1...","{'word': '전년', 'start_idx': 143, 'end_idx': 14...",100,wikitree
7762,7762,"한국전기안전공사(사장 조성완)는 8월 1일부로, 3급 간부직원에 대한 승진·이동 인...","{'word': '한국전기안전공사', 'start_idx': 0, 'end_idx'...","{'word': '조성완', 'start_idx': 12, 'end_idx': 14...",100,wikitree
7763,7763,1987년 B. 슈나이더(B. Schneider)에 의해 만들어졌다.,"{'word': 'B. 슈나이더', 'start_idx': 6, 'end_idx':...","{'word': '1987년', 'start_idx': 0, 'end_idx': 4...",100,wikipedia
7764,7764,이승옥 강진군수는 2일 NH농협은행 강진군지부(지부장 강대형)를 방문해 부품·소재·...,"{'word': '이승옥', 'start_idx': 0, 'end_idx': 2, ...","{'word': '2일', 'start_idx': 10, 'end_idx': 11,...",100,wikitree

In [180]:
# sbm = pd.read_csv("softvoting_1-to-8.csv")
# sbm = pd.read_csv("roberta-large_bs-32_no-split.csv")
sbm = pd.read_csv("output1.csv")
# sbm = pd.read_csv("softvoting_upper4.csv")
sbm

,id,pred_label,probs
0,0,org:product,"[0.22033505735453218, 0.0035056326451012865, 0..."
1,1,per:alternate_names,"[0.039945486234501004, 0.0025147269261651672, ..."
2,2,no_relation,"[0.9978631883859634, 5.732257682211639e-05, 0...."
3,3,no_relation,"[0.9326883405447006, 0.00034784129820764065, 0..."
4,4,no_relation,"[0.7735384553670883, 0.2168797659687698, 0.000..."
...,...,...,...
7760,7760,org:place_of_headquarters,"[0.06964680086821318, 0.0011357328148733359, 0..."
7761,7761,no_relation,"[0.9727324545383453, 0.002246059477329254, 0.0..."
7762,7762,org:top_members/employees,"[0.00010942212952613772, 0.9977824240922928, 9..."
7763,7763,no_relation,"[0.798504039645195, 0.0004021839631604962, 0.0..."
7764,7764,no_relation,"[0.9790358543395996, 0.005540059712075163, 0.0..."

In [181]:
labels = sbm['pred_label']
# labels

In [182]:
tags_sbj = test['subject_entity']
tags_obj = test['object_entity']
# print(tags_sbj)
# print(tags_obj)

In [183]:
mismatched = []
for idx, (sbj, obj, label) in enumerate(zip(tags_sbj, tags_obj, labels)):
    if label != 'no_relation':
        sbj_tags = ['per', 'org']
        obj_tags = ['per', 'org', 'poh', 'dat', 'noh', 'loc']
        
        per_tags = ['per', 'org', 'poh', 'dat', 'noh', 'loc']
        org_tags = ['per', 'org', 'poh', 'dat', 'noh', 'loc']
        
        sbj_type_idx = sbj.index('type')
        obj_type_idx = obj.index('type')
        sbj_type = sbj[sbj_type_idx+8 : sbj_type_idx+11].lower()
        obj_type = obj[obj_type_idx+8 : obj_type_idx+11].lower()
        
        if (sbj_type not in sbj_tags) or (obj_type not in obj_tags):
            print(f"wrong indexing in index {idx}")
            print(sbj_type, obj_type)
        else:
            if sbj_type not in label:
                mismatched.append([idx, sbj_type, obj_type, label])
            else:
                if sbj_type == 'per':
                    if obj_type not in per_tags:
                        mismatched.append([idx, sbj_type, obj_type, label])
                elif sbj_type == 'org':
                    if obj_type not in org_tags:
                        mismatched.append([idx, sbj_type, obj_type, label])
mismatched

[[138, 'per', 'org', 'org:place_of_headquarters'],
 [201, 'org', 'poh', 'per:colleagues'],
 [235, 'org', 'loc', 'per:origin'],
 [373, 'org', 'poh', 'per:alternate_names'],
 [395, 'org', 'dat', 'per:alternate_names'],
 [869, 'org', 'org', 'per:employee_of'],
 [1091, 'per', 'poh', 'org:top_members/employees'],
 [1132, 'org', 'loc', 'per:origin'],
 [1584, 'per', 'poh', 'org:top_members/employees'],
 [1637, 'org', 'per', 'per:children'],
 [2126, 'org', 'loc', 'per:origin'],
 [2234, 'org', 'per', 'per:alternate_names'],
 [2270, 'org', 'poh', 'per:title'],
 [2658, 'org', 'per', 'per:other_family'],
 [3500, 'org', 'org', 'per:employee_of'],
 [3534, 'org', 'noh', 'per:product'],
 [3750, 'org', 'loc', 'per:origin'],
 [4110, 'per', 'poh', 'org:product'],
 [4223, 'per', 'poh', 'org:product'],
 [4375, 'org', 'per', 'per:religion'],
 [5068, 'org', 'org', 'per:alternate_names'],
 [5094, 'org', 'poh', 'per:title'],
 [5265, 'org', 'per', 'per:employee_of'],
 [5267, 'org', 'org', 'per:schools_attended'],
 [5300, 'org', 'loc', 'per:origin'],
 [5507, 'per', 'loc', 'org:place_of_headquarters'],
 [6064, 'org', 'loc', 'per:employee_of'],
 [6255, 'org', 'org', 'per:employee_of'],
 [6386, 'org', 'loc', 'per:origin'],
 [6594, 'org', 'loc', 'per:origin'],
 [6667, 'per', 'loc', 'org:place_of_headquarters'],
 [6717, 'per', 'loc', 'org:place_of_headquarters'],
 [6835, 'org', 'per', 'per:alternate_names'],
 [6876, 'per', 'poh', 'org:product'],
 [6945, 'org', 'poh', 'per:title'],
 [7014, 'org', 'poh', 'per:title'],
 [7106, 'org', 'poh', 'per:title'],
 [7311, 'org', 'poh', 'per:employee_of']]

In [184]:
len(mismatched)

38